import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Map from "../components/parts/Map";
import MenuBar from "../components/parts/MenuBar";

export default function Home(data) {
  return (
    <Box h="100vh" overflow="hidden">
      <Head>
        <title>gomibako</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuBar />
      <Map gomiData={data} />
    </Box>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`http://10.11.11.77/json/gomi.json`);
  const data = await res.json();

  return { props: { data } };
}
