import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Map from "../components/parts/Map";
import MenuBar from "../components/parts/MenuBar";

export default function Home() {
  return (
    <Box h="100vh" overflow="hidden">
      <Head>
        <title>gomibako</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuBar />
      <Map />
    </Box>
  );
}
